# Top-level configuration
name = "trabajodigno-backend"
main = "dist/worker.js" # Point to our new worker entry point
compatibility_date = "2025-04-30"
compatibility_flags = ["nodejs_compat"]

# Remove the build section entirely to skip the build process
# We'll use the pre-built worker.js file directly