# Top-level configuration
name = "trabajodigno-backend" # Replace with your worker name
main = "dist/main.js" # Point to the output of npm run build
compatibility_date = "2025-04-30" # Updated to a recent date for better Node.js compatibility
compatibility_flags = ["nodejs_compat"] # Enable Node.js compatibility
no_bundle = true # Tell Wrangler NOT to bundle the output of the build command

# Re-added build section to run NestJS build
[build]
command = "npm run build" # Command to build your NestJS application
cwd = "." # Directory containing package.json

# Optional: Add environment variables, secrets, KV namespaces, etc. here
# [vars]
# MY_VAR = "my-value"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "your_kv_namespace_id"