# Top-level configuration
name = "trabajodigno-backend"
main = "dist/worker.js"
compatibility_date = "2025-04-30"
compatibility_flags = ["nodejs_compat"]

# Be explicit about nodejs compatibility
node_compat = true