# Top-level configuration
name = "trabajodigno-backend"
main = "dist/worker.js"
compatibility_date = "2025-04-30"
compatibility_flags = ["nodejs_compat"]

# Note: You can ignore the VS Code warnings from the "Even Better TOML" extension.
# The node_compat property is valid according to Cloudflare documentation,
# but the extension's schema may be outdated.